### PR TITLE
prepare for crystal deps

### PR DESCRIPTION
**Pull request by weskinner**

### CODE REVIEW

**Comment by TheBlueCrane** [comment]
Looks like you've done some good work, thanks!

**Comment by weskinner** [comment]
:+1: 

After talking with @asterite, we've moved the official crystal sdl2 library to https://github.com/weskinner/crystal-sdl2.  I will be continuing my dev in that repo.

**Comment by asterite** [comment]
Thanks!!

Yes, let's please keep that repo as the single repo for sdl2 so we can better use our combined efforts :-)

**Comment by TheBlueCrane** [comment]
Awesome, good luck! README.md now includes a link to the new repo, but at some stage I'll remove this repo to reduce confusion.

**Pull request merged**
